# Throwing exceptions

When you want to throw an error, you first need to create a new instance of an exception. Then you use the special `throw` keyword to throw the exception. After this, the runtime will start looking for catch and finally blocks.

```csharp
public static string OpenAndParse(string fileName)
{
    if (string.IsNullOrWhiteSpace(fileName))
        throw new ArgumentNullException("fileName", "Filename is required");
    return File.ReadAllText(fileName);
}
```

## Use cases

Programmers should throw exceptions when one or more of the following conditions are true:

### 1. The method cannot complete its defined functionality

For example, if a parameter to a method has an invalid value:

```csharp
static void CopyObject(SampleClass original)
{
    if (original == null)
    {
        throw new System.ArgumentException("Parameter cannot be null", "original");
    }

}
```

### 2. An inappropriate call to an object is made, based on the object state

One example might be trying to write to a read-only file. In cases where an object state does not allow an operation, throw an instance of InvalidOperationException or an object based on a derivation of this class. This is an example of a method that throws an InvalidOperationException object:

```csharp
class ProgramLog
{
    System.IO.FileStream logFile = null;
    void OpenLog(System.IO.FileInfo fileName, System.IO.FileMode mode) {}

    void WriteLog()
    {
        if (!this.logFile.CanWrite)
        {
            throw new System.InvalidOperationException("Logfile cannot be read-only");
        }
        // Else write data to the log and return.
    }
}
```

## Rethrowing exceptions

When catching an exception, you can choose to rethrow the exception. You have three ways of doing this:

### Use the throw keyword without an identifer

This option rethrows the exception without modifying the call stack.

```csharp
try
{
    SomeOperation();
}
catch (Exception logEx)
{
    // do some loggin
    throw; // rethrow the original exception
}
```

### Use the throw keyword with the original exception

This option resets the callstack to the current location in code. So you canâ€™t see where the exception originally came from, and it is harder to debug the error.

```csharp
try
{
    SomeOperation();
}
catch (Exception logEx)
{
    // Do some loggin
    throw new Exception("you passed in bad data"); // resets stacktrace
}
```

### Throwing an Exception with an Inner Exception

An exception can be thrown along with an inner exception by passing the inner exception in the second parameter of the newly arised exception. Also, if you throw a new exception with the initial exception you will preserve the initial stack trace too.

```csharp
try
{
    SomeOperation();
}
catch (Exception innerEx)
{
    // do some loggin
    throw new ArgumentException("you passed in bad data", innerEx); // new exception, with original exception
}
```

## Things to Avoid When Throwing Exceptions

The following list identifies practices to avoid when throwing exceptions:

* Exceptions should not be used to change the flow of a program as part of ordinary execution. Exceptions should only be used to report and handle error conditions.
* Exceptions should not be returned as a return value or parameter instead of being thrown.
* Do not throw `System.Exception`, `System.SystemException`, `System.NullReferenceException`, or `System.IndexOutOfRangeException` intentionally from your own source code.
* Do not create exceptions that can be thrown in debug mode but not release mode.